package com.example.gj.config.response;

public class Message {
    public static final String INVALID_EMAIL = "Invalid Email.";
    public static final String VERIFY_FAIL = "verify fail";
    public static final String CREATE_VERIFY_FAIL = "create verify fail";
    public static final String CODE_LENGTH = "Invalid code length";
    public static final String EXPIRE_CODE = "Expire code";
    public static final String WAIT = "Wait a few minute to resend code";
    public static final String VERIFIED = "Verified account";
    public static final String INVALID_CODE = "Invalid Code";
    public static final String LOGIN_FAIL = "Invalid email or password";
    public static final String INVALID_PASSWORD = "The password has an invalid format!";
    public static final String PASSWORD_SHORT = "Password is too short!";
    public static final String INVALID_CONFIRM_PASSWORD = "The confirm password has an invalid format!";
    public static final String PASSWORD_NOT_MATCH = "New password and confirm password not match!";
    public static final String INVALID_ROLE = "Invalid Role.";
    public static final String INVALID_STATUS = "Invalid Status.";
    public static final String INVALID_FULL_NAME = "Invalid Full Name.";
    public static final String INVALID_GENDER = "Invalid Gender.";
    public static final String INVALID_PHONE = "Invalid Phone.";
    public static final String INVALID_ADDRESS_NAME = "Invalid Address Name.";
    public static final String INVALID_ADDRESS = "Invalid Address.";
    public static final String INVALID_SKILL_NAME = "Invalid Skill Name.";
    public static final String INVALID_JOB_TITLE = "Invalid Job Title.";
    public static final String INVALID_CV_DETAIL_SUMMARY = "Invalid CV Summary.";
    public static final String INVALID_CV_DETAIL_ADDRESS = "Invalid Address.";
    public static final String INVALID_POSITION_NAME = "Invalid Position Name.";
    public static final String INVALID_QUESTION = "Invalid Question.";
    public static final String INVALID_AVATAR = "Invalid Avatar";
    public static final String INVALID_CERTIFICATE = "Invalid Certificate";
    public static final String CREATE_FAILED = "Failed To Create";
    public static final String CREATE_LIST_SUCCESSFULLY = "Create List Successfully";
    public static final String EMPTY_LIST_WITH_KEYWORD = "Cannot Find %s List With %s";
    public static final String EMPTY_LIST = "Cannot Find %s List";
    public static final String EMPTY_OBJECT = "Cannot Find %s";
    public static final String EMPTY_OBJECT_WITH_ID = "Cannot Find %s With %d";
    public static final String USER_NOT_FOUND = "User Cannot Be Found";
    public static final String EMAIL_EXISTED = "Email is Exist";
    public static final String NULL_INPUT = "Input Cannot Be Null";
    public static final String INVALID_USER = "User not found";
    public static final String CREATE_SUCCESSFULLY = "Create Successfully";
    public static final String FIND_SUCCESSFULLY = "Find %s Successfully";
    public static final String UPDATE_SUCCESSFULLY = "Update Successfully";
    public static final String INVALID_PAGE_NUMBER = "Page Number Must Be Greater Than 0";
    public static final String INVALID_PER_PAGE_NUMBER = "Per Page Number Must Be Greater Than 0";
    public static final String JOB_EXISTED = "Job Already Existed";
    public static final String OBJECT_NOT_FOUND = "%s Not Found";
    public static final String VERIFY_NOT_FOUND = "Verify is not found";
    public static final String INVALID_CV_Id = "ID's CV not exist";
    public static final String INCORRECT_OLD_PASSWORD = "Old password is incorrect";
    public static final String DIFFERENT_PASSWORD ="The new password must be different from the old password";
    public static final String INVALID_QUESTION_Id = "ID's Question not exist";
    public static final String OBJECT_NOT_FOUND_WITH_ID = "%s Not Found With %d";
    public static final String LOGIN_SUCCESSFULLY = "Login success";
    public static final String INVALID_TOKEN = "Token is invalid!";
    public static final String EXPIRED_TOKEN = "Token is expired!";
    public static final String CONVERT_SUCCESSFULLY = "Convert Successfully";
    public static final String INVALID_SKILL = "Invalid Skill";
    public static final String INVALID_SKILL_ID = "Id = %d is not exist";
    public static final String SAVE_SUCCESSFULLY = "Save Successfully";
    public static final String WRONG_ROLE = "User does not have INTERVIEWER permission";


}
